### ISSUE TITLE
Q: most efficient way to update and merge state

### ISSUE THREAD

**Issue by SpareShade** [avkonst/react-use-state-x#244]
Hello @avkonst 
Thank you for this pretty & tiny tool!

I'm using the "wrapped state" approach you flashed-out in some of your examples.

I am wondering what is the best approach for adding records to an array based state using this library.
Eg. I've pulled a number of tasks from the server. Some of these are already present in my local store, but need to be updated in case they were changed, and some are new and need to be added to the store.

I think my approach below re-renders the parent component for each loop in the map that adds/merges tasks to the state.

Add tasks method below:

```javascript
  addTasks: (tasks: Task[]) => {
    tasks.map((taskToAdd) => {
      const index = s.findIndex(
        (storedTask) => storedTask.id.value === taskToAdd.id
      );
      if (index === -1) {
        //
        s.merge([taskToAdd]);
      } else {
        s[index].set(taskToAdd);
      }
    });
  },
```

Any suggestion is much appreciated.

**Comment by avkonst** [comment]
Please check the documentation about merge function. It can add, update and
delete items from an array in one call. Alternatively, you can also use
batch method of a state. Let me know if it is still unclear.
