### ISSUE TITLE
one of my favourite projects really

### ISSUE THREAD

**Issue by hp8wvvvgnj6asjm7** [avkonst/react-use-state-x#392]
hope this won't get abandoned.

**Comment by avkonst** [comment]
I will live!

**Comment by avkonst** [comment]
but help from the community would help to get the load off

**Comment by avkonst** [comment]
same domain, but different trade offs. They use selectors to optimize performance. Hookstate uses proxies and special unique hash tree to identify rerender targets in the most efficient way in a large data set (like a table with 10K cells)
